location: mount/config
sources:
  - repo: git@github.com:jimeh/tmux-themepack.git
    name: tmux-themepack
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      -
default_group: ''
groups:
  -